"""feat(user): add password hash

Revision ID: 957a327e2a7f
Revises: 3598e99c8b51
Create Date: 2026-05-25 19:31:03.927979

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "957a327e2a7f"
down_revision = "3598e99c8b51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
